# -*- cperl -*-
package XLDB::OFile;

=head1 NAME

XLDB::OFile -- excel output file with easy and consistent formatting facilities

=cut

require 5.006;
use XLDB::File;
use parent 'XLDB::File';

require Excel::Writer::XLSX;
require Excel::Writer::XLSX::Utility;
require XLDB::Sheet;

use Data::Dumper;

use strict;

sub new {
  my $class = shift;
  my %args = @_;
  die( "Error: missing arguments on construction of XLDB::OFile\n" )
    unless( exists $args{filename} and exists $args{title} and 
	    exists $args{author} and exists $args{company} and 
	    exists $args{division} and exists $args{toolname} );

  my $self = {};
  $self->{Sheets} = {};
  $self->{Filename} = $args{filename};
  $self->{Title} = $args{title};
  $self->{Author} = $args{author};
  $self->{Company} = $args{company};
  $self->{Division} = $args{division};
  $self->{Toolname} = "Generated by " . $args{toolname};
  $self->{Book} = Excel::Writer::XLSX->new( $args{filename} )
    or die( "Error: cannot open excel book '$args{filename}' for writing\n" );
  $self->{Book}->set_properties( title    => $self->{Title},
				 author   => $self->{Author},
				 manager  => $self->{Author},
				 company  => $self->{Company},
				 category => $self->{Division},
				 comments => $self->{Toolname},
			       );

  bless( $self, $class );

  $self->_generateFormats();

  return $self;
}

sub format {
  my $self = shift;
  my ( $formatstring ) = @_;
  return undef unless( defined $formatstring );

  if ( exists $self->{fmt}->{$formatstring} ) {
    return $self->{fmt}->{$formatstring};
  }
  else {
    warn( "Warning: format '$formatstring' unknown" );
    return undef;
  }
}

sub makeSheet {
  my $self = shift;
  my ( $sheetname, $orientation ) = @_;

  $self->{Sheets}->{$sheetname} = XLDB::Sheet->new( $sheetname, $orientation, $self )
    or die( "Error: could not add worksheet '$sheetname' " .
	    "to excel book '$self->{Filename}'\n" );
  $self->{Sheets}->{$sheetname}->{Sheet}->set_zoom( 80 );

  return $self->sheet( $sheetname );
}

sub close {
  my $self = shift;

  while( my ( $sheetname, $sheet ) = each %{$self->{Sheets}} ) {
    $sheet->close( $self->{Toolname}, $self->{Company}, $self->{Division} );
  }

  $self->{Book}->close();
}

sub _generateFormats {
  my $self = shift;
  $self->{fmt} = {};

  # principles:
  # <alignment><style><format>
  # <alignment> can be any of: 
  #   <empty> = left, L = left, LI = left indented, C = center, 
  #   R = right, RI = right indented, T = roTated
  # <style> can be any of:
  #   b = bold, x = white on black, g = white on grey,
  #   t = title (= bold, larger font), u = underlined ( bold, underlined cell)
  #   a = boxed (bold, lines all around)
  # <format> can be any of:
  #   <empty> = no particular format
  #   P0 = percentage, 0 decimals, P1 = percentage, 1 decimal, 
  #   P2 = percentage, 2 decimals
  #   F0 = fixed point 0 decimals, F1 = fixed point 1 decimal, 
  #   F2 = fixed point 2 decimals
  $self->{fmt}->{b} = $self->{Book}->add_format();
  $self->{fmt}->{b}->set_bold();

  $self->{fmt}->{t} = $self->{Book}->add_format();
  $self->{fmt}->{t}->set_bold();
  $self->{fmt}->{t}->set_size( 14 );

  $self->{fmt}->{L} = $self->{Book}->add_format();
  $self->{fmt}->{L}->set_align( 'left' );
  $self->{fmt}->{L}->set_align( 'top' );

  $self->{fmt}->{Lb} = $self->{Book}->add_format();
  $self->{fmt}->{Lb}->set_align( 'left' );
  $self->{fmt}->{Lb}->set_align( 'top' );
  $self->{fmt}->{Lb}->set_bold();

  $self->{fmt}->{Lx} = $self->{Book}->add_format();
  $self->{fmt}->{Lx}->set_align( 'left' );
  $self->{fmt}->{Lx}->set_align( 'top' );
  $self->{fmt}->{Lx}->set_bold();
  $self->{fmt}->{Lx}->set_bg_color( 'black' );
  $self->{fmt}->{Lx}->set_color( 'white' );

  $self->{fmt}->{Lu} = $self->{Book}->add_format();
  $self->{fmt}->{Lu}->set_bold();
  $self->{fmt}->{Lu}->set_align( 'left' );
  $self->{fmt}->{Lu}->set_align( 'bottom' );
  $self->{fmt}->{Lu}->set_bottom( 2 );

  $self->{fmt}->{La} = $self->{Book}->add_format();
  $self->{fmt}->{La}->set_bold();
  $self->{fmt}->{La}->set_align( 'left' );
  $self->{fmt}->{La}->set_align( 'bottom' );
  $self->{fmt}->{La}->set_border( 2 );

  $self->{fmt}->{LxP0} = $self->{Book}->add_format();
  $self->{fmt}->{LxP0}->set_align( 'left' );
  $self->{fmt}->{LxP0}->set_align( 'top' );
  $self->{fmt}->{LxP0}->set_bold();
  $self->{fmt}->{LxP0}->set_bg_color( 'black' );
  $self->{fmt}->{LxP0}->set_color( 'white' );
  $self->{fmt}->{LxP0}->set_num_format( '0%' );

  $self->{fmt}->{LxP1} = $self->{Book}->add_format();
  $self->{fmt}->{LxP1}->set_align( 'left' );
  $self->{fmt}->{LxP1}->set_align( 'top' );
  $self->{fmt}->{LxP1}->set_bold();
  $self->{fmt}->{LxP1}->set_bg_color( 'black' );
  $self->{fmt}->{LxP1}->set_color( 'white' );
  $self->{fmt}->{LxP1}->set_num_format( '0.0%' );

  $self->{fmt}->{LxP2} = $self->{Book}->add_format();
  $self->{fmt}->{LxP2}->set_align( 'left' );
  $self->{fmt}->{LxP2}->set_align( 'top' );
  $self->{fmt}->{LxP2}->set_bold();
  $self->{fmt}->{LxP2}->set_bg_color( 'black' );
  $self->{fmt}->{LxP2}->set_color( 'white' );
  $self->{fmt}->{LxP2}->set_num_format( '0.00%' );

  $self->{fmt}->{Lg} = $self->{Book}->add_format();
  $self->{fmt}->{Lg}->set_align( 'left' );
  $self->{fmt}->{Lg}->set_align( 'top' );
  $self->{fmt}->{Lg}->set_bold();
  $self->{fmt}->{Lg}->set_bg_color( 23 );
  $self->{fmt}->{Lg}->set_color( 'white' );

  $self->{fmt}->{LgP0} = $self->{Book}->add_format();
  $self->{fmt}->{LgP0}->set_align( 'left' );
  $self->{fmt}->{LgP0}->set_align( 'top' );
  $self->{fmt}->{LgP0}->set_bold();
  $self->{fmt}->{LgP0}->set_bg_color( 23 );
  $self->{fmt}->{LgP0}->set_color( 'white' );
  $self->{fmt}->{LgP0}->set_num_format( '0%' );

  $self->{fmt}->{LgP1} = $self->{Book}->add_format();
  $self->{fmt}->{LgP1}->set_align( 'left' );
  $self->{fmt}->{LgP1}->set_align( 'top' );
  $self->{fmt}->{LgP1}->set_bold();
  $self->{fmt}->{LgP1}->set_bg_color( 23 );
  $self->{fmt}->{LgP1}->set_color( 'white' );
  $self->{fmt}->{LgP1}->set_num_format( '0.0%' );

  $self->{fmt}->{LgP2} = $self->{Book}->add_format();
  $self->{fmt}->{LgP2}->set_align( 'left' );
  $self->{fmt}->{LgP2}->set_align( 'top' );
  $self->{fmt}->{LgP2}->set_bold();
  $self->{fmt}->{LgP2}->set_bg_color( 23 );
  $self->{fmt}->{LgP2}->set_color( 'white' );
  $self->{fmt}->{LgP2}->set_num_format( '0.00%' );

  $self->{fmt}->{C} = $self->{Book}->add_format();
  $self->{fmt}->{C}->set_align( 'center' );
  $self->{fmt}->{C}->set_align( 'top' );

  $self->{fmt}->{Cb} = $self->{Book}->add_format();
  $self->{fmt}->{Cb}->set_align( 'center' );
  $self->{fmt}->{Cb}->set_align( 'top' );
  $self->{fmt}->{Cb}->set_bold();

  $self->{fmt}->{Cx} = $self->{Book}->add_format();
  $self->{fmt}->{Cx}->set_align( 'center' );
  $self->{fmt}->{Cx}->set_align( 'top' );
  $self->{fmt}->{Cx}->set_bold();
  $self->{fmt}->{Cx}->set_bg_color( 'black' );
  $self->{fmt}->{Cx}->set_color( 'white' );

  $self->{fmt}->{Cu} = $self->{Book}->add_format();
  $self->{fmt}->{Cu}->set_bold();
  $self->{fmt}->{Cu}->set_align( 'center' );
  $self->{fmt}->{Cu}->set_align( 'bottom' );
  $self->{fmt}->{Cu}->set_bottom( 2 );

  $self->{fmt}->{Ca} = $self->{Book}->add_format();
  $self->{fmt}->{Ca}->set_bold();
  $self->{fmt}->{Ca}->set_align( 'center' );
  $self->{fmt}->{Ca}->set_align( 'bottom' );
  $self->{fmt}->{Ca}->set_border( 2 );

  $self->{fmt}->{R} = $self->{Book}->add_format();
  $self->{fmt}->{R}->set_align( 'right' );
  $self->{fmt}->{R}->set_align( 'top' );

  $self->{fmt}->{Rb} = $self->{Book}->add_format();
  $self->{fmt}->{Rb}->set_align( 'right' );
  $self->{fmt}->{Rb}->set_bold();

  $self->{fmt}->{Rx} = $self->{Book}->add_format();
  $self->{fmt}->{Rx}->set_align( 'right' );
  $self->{fmt}->{Rx}->set_align( 'top' );
  $self->{fmt}->{Rx}->set_bold();
  $self->{fmt}->{Rx}->set_bg_color( 'black' );
  $self->{fmt}->{Rx}->set_color( 'white' );

  $self->{fmt}->{Ru} = $self->{Book}->add_format();
  $self->{fmt}->{Ru}->set_bold();
  $self->{fmt}->{Ru}->set_align( 'right' );
  $self->{fmt}->{Ru}->set_align( 'bottom' );
  $self->{fmt}->{Ru}->set_bottom( 2 );

  $self->{fmt}->{Ra} = $self->{Book}->add_format();
  $self->{fmt}->{Ra}->set_bold();
  $self->{fmt}->{Ra}->set_align( 'right' );
  $self->{fmt}->{Ra}->set_align( 'bottom' );
  $self->{fmt}->{Ra}->set_border( 2 );

  $self->{fmt}->{LI1} = $self->{Book}->add_format();
  $self->{fmt}->{LI1}->set_align( 'left' );
  $self->{fmt}->{LI1}->set_align( 'top' );
  $self->{fmt}->{LI1}->set_indent( 1 );

  $self->{fmt}->{LI2} = $self->{Book}->add_format();
  $self->{fmt}->{LI2}->set_align( 'left' );
  $self->{fmt}->{LI2}->set_align( 'top' );
  $self->{fmt}->{LI2}->set_indent( 2 );

  $self->{fmt}->{RI1} = $self->{Book}->add_format();
  $self->{fmt}->{RI1}->set_align( 'right' );
  $self->{fmt}->{RI1}->set_align( 'top' );
  $self->{fmt}->{RI1}->set_indent( 1 );

  $self->{fmt}->{RI2} = $self->{Book}->add_format();
  $self->{fmt}->{RI2}->set_align( 'right' );
  $self->{fmt}->{RI2}->set_align( 'top' );
  $self->{fmt}->{RI2}->set_indent( 2 );

  $self->{fmt}->{RI1P1} = $self->{Book}->add_format();
  $self->{fmt}->{RI1P1}->set_align( 'right' );
  $self->{fmt}->{RI1P1}->set_align( 'top' );
  $self->{fmt}->{RI1P1}->set_indent( 1 );
  $self->{fmt}->{RI1P1}->set_num_format( '0.0%' );

  $self->{fmt}->{RI1F1} = $self->{Book}->add_format();
  $self->{fmt}->{RI1F1}->set_align( 'right' );
  $self->{fmt}->{RI1F1}->set_align( 'top' );
  $self->{fmt}->{RI1F1}->set_indent( 1 );
  $self->{fmt}->{RI1F1}->set_num_format( '0.0' );

  $self->{fmt}->{LI1b} = $self->{Book}->add_format();
  $self->{fmt}->{LI1b}->set_align( 'left' );
  $self->{fmt}->{LI1b}->set_align( 'top' );
  $self->{fmt}->{LI1b}->set_indent( 1 );
  $self->{fmt}->{LI1b}->set_bold();

  $self->{fmt}->{RI1b} = $self->{Book}->add_format();
  $self->{fmt}->{RI1b}->set_align( 'right' );
  $self->{fmt}->{RI1b}->set_align( 'top' );
  $self->{fmt}->{RI1b}->set_indent( 1 );
  $self->{fmt}->{RI1b}->set_bold();

  $self->{fmt}->{RI1bF1} = $self->{Book}->add_format();
  $self->{fmt}->{RI1bF1}->set_align( 'right' );
  $self->{fmt}->{RI1bF1}->set_align( 'top' );
  $self->{fmt}->{RI1bF1}->set_indent( 1 );
  $self->{fmt}->{RI1bF1}->set_bold();
  $self->{fmt}->{RI1bF1}->set_num_format( '0.0' );

  $self->{fmt}->{LI1x} = $self->{Book}->add_format();
  $self->{fmt}->{LI1x}->set_align( 'left' );
  $self->{fmt}->{LI1x}->set_indent( 1 );
  $self->{fmt}->{LI1x}->set_bold();
  $self->{fmt}->{LI1x}->set_bg_color( 'black' );
  $self->{fmt}->{LI1x}->set_color( 'white' );

  $self->{fmt}->{RI1x} = $self->{Book}->add_format();
  $self->{fmt}->{RI1x}->set_align( 'right' );
  $self->{fmt}->{RI1x}->set_indent( 1 );
  $self->{fmt}->{RI1x}->set_bold();
  $self->{fmt}->{RI1x}->set_bg_color( 'black' );
  $self->{fmt}->{RI1x}->set_color( 'white' );

  $self->{fmt}->{LW} = $self->{Book}->add_format();
  $self->{fmt}->{LW}->set_align( 'left' );
  $self->{fmt}->{LW}->set_align( 'top' );
  $self->{fmt}->{LW}->set_text_wrap( 1 );

  $self->{fmt}->{T} = $self->{Book}->add_format();
  $self->{fmt}->{T}->set_rotation( 90 );
  $self->{fmt}->{T}->set_align( 'center' );

  $self->{fmt}->{Tb} = $self->{Book}->add_format();
  $self->{fmt}->{Tb}->set_bold();
  $self->{fmt}->{Tb}->set_rotation( 90 );
  $self->{fmt}->{Tb}->set_align( 'center' );

  $self->{fmt}->{Tu} = $self->{Book}->add_format();
  $self->{fmt}->{Tu}->set_bold();
  $self->{fmt}->{Tu}->set_rotation( 90 );
  $self->{fmt}->{Tu}->set_align( 'center' );
  $self->{fmt}->{Tu}->set_bottom( 2 );

  $self->{fmt}->{link} = $self->{Book}->add_format( color => 'blue' );
}




1;

__END__

=head1 SEE ALSO

 --

=head1 COPYRIGHT

 CONFIDENTIAL AND PROPRIETARY (C) 2013 Walter Daems / Digital Manifold Waves

=head1 AUTHOR

 Digital Manifold Waves -- F<walter@digmanwaves.net>

=cut
